/*
  ____  _       _            _             _       
 / ___|(_)_ __ | | __  _ __ | |_   _  __ _(_)_ __  
 \___ \| | '_ \| |/ / | '_ \| | | | |/ _` | | '_ \ 
  ___) | | | | |   <  | |_) | | |_| | (_| | | | | |
 |____/|_|_| |_|_|\_\ | .__/|_|\__,_|\__, |_|_| |_|
                      |_|            |___/         
# A Template for Hdf5Plugin, a Sink Plugin
# Generated by the command: plugin --type sink --dir hdf5_plugin --install-dir /Users/p4010/usr/local HDF5
# Hostname: Fram-IV-2.local
# Current working directory: /Users/p4010/Develop/MADS_plugins
# Creation date: 2025-07-09T12:52:15.976+0200
# NOTICE: MADS Version 1.3.1
*/

// Mandatory included headers
#include <sink.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <H5Cpp.h>
#include <sstream>
#include "json2hdf5.hpp"
// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "hdf5"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Hdf5Plugin : public Sink<json> {

public:
  ~Hdf5Plugin() {
    // Constructor implementation, if needed
    try {
      _converter.close();
    } catch (const H5::Exception &e) {
      _error = "Error closing HDF5 file: " + string(e.getDetailMsg());
    }
  }

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    if (std::find(_converter.groups().begin(), _converter.groups().end(), topic) == _converter.groups().end()) {
      _error = "Topic '" + topic + "' not found in keypaths.";
      return return_type::retry;
    }
    try {
      _converter.save_to_group(input, topic);
    } catch (const std::exception &e) {
      _error = "Error converting JSON to HDF5: " + string(e.what());
      return return_type::warning;
    } 
    return return_type::success;
  }

  void set_params(const json &params) override { 
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Sink::set_params(params);

    // provide sensible defaults for the parameters by setting e.g.
    _params["filename"] = "mads_log.h5";
    _params["keypath_sep"] = "."; // Default keypath separator
    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(params);

    _converter.open(_params["filename"].get<string>());
    _converter.set_keypath_separator(_params["keypath_sep"].get<string>());
    for (const auto &group : _params["keypaths"].items()) {
      for (const auto &keypath : group.value()) {
        _converter.append_keypath(keypath.get<string>(), group.key());
      }
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    map<string, string> info_map;
    info_map["File name"] = _params["filename"];
    stringstream ss;
    size_t total_keypaths = 0;
    for (const auto &group : _converter.groups()) {
      for (const auto &keypath : _converter.keypaths(group)) {
        ss << group << _converter.keypath_separator() << keypath << ", ";
      }
      total_keypaths += _converter.keypaths(group).size();
    }
    if (!ss.str().empty()) {
      ss.seekp(-2, ss.cur); // Remove the last comma and space
    }
    ss << " (total: " << total_keypaths << ")";
    info_map["Keypaths"] = ss.str();
    info_map["Keypath sep."] = _converter.keypath_separator();
    return info_map;
  };

private:
  // Define the fields that are used to store internal resources
  JsonToHdf5Converter _converter; // Converter for JSON to HDF5
};



/*
  ____  _             _             _      _                
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __ 
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |   
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|   
                |___/                                      
Enable the class as plugin 
*/
INSTALL_SINK_DRIVER(Hdf5Plugin, json)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
#include "unit_tests.hpp"
using namespace Mads;

int main(int argc, char const *argv[]) {
  cout << "====================================" << endl;
  cout << "Running unit tests for Hdf5Plugin..." << endl;
  cout << "Plugin kind: " << Hdf5Plugin().kind() << endl;
  cout << "Protocol version: " << Hdf5Plugin::version << endl;
  cout << "Server name: " << Hdf5Plugin::server_name() << endl;
  cout << "====================================\n" << endl;

  int failures = 0, tests = 0;
  json input = {
    {"timecode", 1234567890},
    {"timestamp", "2025-07-09T12:52:15.976+0200"},
    {"hostname", "Fram-IV.local"},
    {"data", {
      {"key1", "value1"}, 
      {"key2", 42}, 
      {"key3", {1, 2, 3, 4, 5}},
      {"key4", {{"subkey1", "subvalue1"}, {"subkey2", "subvalue2"}}}
    }}
  };
  json params = {
    {"filename", "test_output.h5"},
    {"keypaths", {
      {"test_topic", {
        "data.key1", "data.key2", "data.key3", "data.key4.subkey1", "data.key4.subkey2"
      }}
    }},
    {"keypath_sep", "."}
  };

  {
    // Test 1: set_params
    Hdf5Plugin plugin;
    failures += !doesnt_throw([&]() { plugin.set_params(params); }, "set_params threw an exception");
    tests++;
  }

  {
    // Test 2: load_data
    Hdf5Plugin plugin;
    plugin.set_params(params);
    failures += !doesnt_throw([&]() { plugin.load_data(input, "test_topic"); }, "load_data threw an exception");
    tests++;
  }

  {
    // Test 3: info
    Hdf5Plugin plugin;
    json params;
    failures += doesnt_throw([&]() { plugin.set_params(params); }, "set_params with empty params didn't threw an exception");
    tests++;

  }
  
  {
    // Test 4: load_data returns success
    Hdf5Plugin plugin;
    plugin.set_params(params);
    require(plugin.load_data(input, "test_topic") == return_type::success, "Failed to load data into Hdf5Plugin");
    tests++;
  }

  cout << "\nUnit tests completed: " << (tests - failures) << "/" << tests << " passed." << endl;
  if (failures > 0) {
    cerr << failures << " unit test(s) failed. Please fix the issues before using the plugin." << endl;
    return 1;
  }
  
  
  return 0;
}
